#!/usr/bin/env node
/**
 * @file
 * Fake PHPCS executable for tests.
 */

const getStdin = require('get-stdin');

getStdin()
  .then((stdin) => {
    console.log(
      JSON.stringify({ arg: process.argv.slice(1).join(' '), stdin }).slice(0, -1),
    );
  })
  .finally(() => process.exit(0));
